### ISSUE TITLE
creacion de lista para almacenar puntaje

### ISSUE THREAD

**Issue by FabrizioR17** [rdev32/python-trivia#3]
podrias crear una lista vacia
lista_puntajes = []
y agregarle los valores de los punatjes finales que le sale al jugador
lista_puntajes.append(puntaje)

**Comment by rdev32** [comment]
esto no se soluciona asi

la lista de los puntajes no se puede almacenar porque en el momento en el que el programa muere los puntajes tambien

se arregla escribiendo los puntajes en otro archivo pero eso ya exede de los conocimientos de este curso 

asi que se quedara asi por el momento
